name: Update Kiro Version Information

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main, master ]
    paths:
      - 'crawler.js'
      - '.github/workflows/update-versions.yml'

jobs:
  update-versions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run crawler script
      run: npm start
      
    - name: Check file changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit updates
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🤖 Auto update Kiro version information - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
        
    - name: Create release tag (if new version)
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        # Get latest version number
        LATEST_VERSION=$(node -e "
          const fs = require('fs');
          try {
            const data = JSON.parse(fs.readFileSync('kiro-versions.json', 'utf8'));
            const versions = Object.values(data.platforms)
              .map(p => p.currentRelease)
              .filter(v => v)
              .sort()
              .reverse();
            console.log(versions[0] || 'unknown');
          } catch(e) {
            console.log('unknown');
          }
        ")
        
        if [ "$LATEST_VERSION" != "unknown" ]; then
          TAG_NAME="data-update-$(date +'%Y%m%d-%H%M%S')"
          git tag -a "$TAG_NAME" -m "Data update: Kiro v$LATEST_VERSION"
          git push origin "$TAG_NAME"
          echo "Created tag: $TAG_NAME"
        fi